import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${manrope.variable} antialiased h-full flex flex-col`}
      >
        <div className="flex-1">
          <div className="bg-[#0A2640] px-24">
            <Navbar />
            <Hero />
          </div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
